image: python:3.6-alpine

pages:
  script:
  - pip install sphinx
  - pip install sphinx-autodoc-typehints
  - python setup.py build_sphinx
  - mv build/sphinx/html public
  artifacts:
    paths:
    - public
  only:
  - master
